### ISSUE TITLE
Evaluation of the generalization performance?

### ISSUE THREAD

**Issue by sunghoonhong** [yobibyte/amorpheus#1]
Hello, Vitaly.

Thanks for your interesting work!

I have 3 questions about how to evaluate the generalization performance in your paper.

1. Did you evaluate the model checkpoint saved at the last (after training)?
I guess you used the last checkpoint as default setting in your code.
But, it is also possible to evaluate other checkpoints saved during training, so could you clarify it?

2. In generalization section in Appendix of your paper, you said, 
> The numbers show the average performance of three seeds evaluated on 100 rollouts and standard error of the mean.  

How did you compute average of three seeds on 100 rollouts ?
I guess you computed the average performance of each seed, and then computed mean and stderr over 3 seeds.
I would like to hear from you and clarify the evaluation method.

3. What kind of model did you evaluate?
The evaluation table contains test sets of ```walkers```, ```humanoids``` and ```cheetahs```.
Did you evaluate the checkpoint of ```walkers```, ```humanoids``` and ```cheetahs``` respectively or only one checkpoint of ```cwhh```?

Thanks for your great work again and I'm looking forward to your reply.

Thank you.

**Comment by yobibyte** [comment]
Hi @sunghoonhong! Thanks for your interest! Please, find the answers below.

1. I took the last checkpoint.
2. > I guess you computed the average performance of each seed, and then computed the mean and stderr over 3 seeds.

Yes, that's how I did that.

3. For walkers++ I evaluated the walker model (check out Table 2 for training/zero-shot split) etc., not the single cwh/cwhh model.

Let me know if you have more questions!

**Comment by sunghoonhong** [comment]
Thanks for your clear answer!

I have run some experiments with your code, but I think there are some typo in _get_obs_per_limb() in environment .py files.
Specifically, for humanoid++, the limb_type_vec is assigned incorrectly, i.e. every limbs are assigned to (0, 0, 0, 0).

In humanoid xmls, the name of limb body belongs to {'torso', '(left/right) shoulder', '(left/right) thigh', '(left/right) shin', '(left/right) upper arm', '(left/right) lower arm'}, but the limb type assignment condition compares the name with {'hip', 'knee', 'shoulder', 'elbow'} which are the names of motor (joint) in your code.

I know the environment codes are from SMP repository, but I'm wondering if this is intended.

**Comment by yobibyte** [comment]
That's a good catch! I was not aware of this.

**Comment by sunghoonhong** [comment]
Thanks for clarification and your great work again!
